### ISSUE TITLE
libreboot download

### ISSUE THREAD

**Issue by leahanderson1** [kkilobyte/ditch-cros#2]
if you go to the download page, there is a list of mirrors that you can use to download the ROM images.
(yes this includes the chromebook ones)
if you need help I can include a download link to the gru bob and gru kevin images.

**Comment by kkilobyte** [comment]
yes please provide them, not sure what to look for in the mirrors for gru

**Comment by kkilobyte** [comment]
oh i might've found the required links! not exactly sure if these are the correct ones to use tho...

https://mirrors.mit.edu/libreboot/stable/20240612/roms/libreboot-20240612_gru_kevin.tar.xz
https://mirrors.mit.edu/libreboot/stable/20240612/roms/libreboot-20240612_gru_bob.tar.xz



even found one for veyron speedy, but im not quite sure if i should include it since it uses depthcharge (so im not sure if it can even boot linux) and its an older build

https://mirrors.mit.edu/libreboot/stable/20160907/rom/depthcharge/libreboot_r20160907_depthcharge_veyron_speedy.tar.xz

**Comment by leahanderson1** [comment]
yep the top 2 are the correct links veryron speedy is probably unmaintained so you should probably not use it

**Comment by kkilobyte** [comment]
> yep the top 2 are the correct links veryron speedy is probably unmaintained so you should probably not use it

are the top 2 u-boot payloads?

**Comment by leahanderson1** [comment]
yes
