### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by antgame11** [kkilobyte/ditch-cros#5]
I have done the fullrom coreboot plenty of times and have installed Ubuntu plenty of times, it's worked fine. Why are you saying Ubuntu doesn't have support?

Also, mentioning theft doesn't seem like a good idea, I would've never thought that people would steal chromebooks to do this UNTIL I read that, it seems like that's your intention for this guide.

**Comment by kkilobyte** [comment]
Ubuntu isn't supported by the Chrultrabook team (which is kinda behind Chromebook on alt OSes), and Ubuntu as an OS is ass (it's Debian Testing with shitty Canonical shit like Snap and telemetry), and Canonical as a company is also ass.

Also Chromebook theft from schools and enterprises has always been a problem, even before the creation of this guide.

**Comment by antgame11** [comment]
In fact, i had better support with ubuntu than I did with arch

**Comment by kkilobyte** [comment]
You might be able to ride on Canonical perfectly fine, however Ubuntu is the distro that is horrid because of Snap and Canonical is a bad company so I couldn't even think of recommending it. And like I said, the Chromebook firmware and driver development team called Chrultrabook doesn't support it.

Arch is a hit or miss, I run into Wayland and RF kill status issues with Arch on Chromebooks, but Arch isn't a beginner distro anyways and it's supported by the Chrultrabook team. I never mentioned Arch in my guide, and those who have the knowledge to fix the issues Arch has are the people who SHOULD be using Arch, not some noob who thinks Ubuntu is a good Linux distro.

I have personally tested Ubuntu 24.10 on my own Chromebook (octopus-phaser360 / Lenovo 300e Chromebook Gen 2 (Intel)), and the lag was so bad and the inability to even install some packages with apt without being told to use Snap was so painful.

I could never recommend Ubuntu due to Canonical's bullshit as a company and an OS developer, and the Chrultrabook team knows this and refuses to support Ubuntu, meaning drivers and firmware might just break with Ubuntu, due to Ubuntu's weirdness

If you wish to still use Ubuntu, go ahead, I'll still feel bad for you though. Debian Testing is the better option as Ubuntu is just Debian Testing with Canonical bullshit, and you can install Gnome on Debian if you wish.

A good Linux distro for Chromebooks would be Ultramarine, like the Chrultrabook developers are in the Ultramarine Discord lmfao, and Gnome versions of Ultramarine exist, I personally use it and it's such a painless distro.

**Comment by antgame11** [comment]
debian based linux distros (or plain debian) is the best imo
